config/routes.rb
Rails101Homework::Application.routes.draw do

  devise_for :users

  resources :boards, :only => [:index, :show] do
    resources :posts, :except => [:index]
  end

  namespace :admin do
    resources :boards, :except => [:show] do
      resources :posts, :only => [:edit, :update, :destroy]
    end
  end

  root :to => "boards#index"

end

app/models/board.rb
class Board < ActiveRecord::Base
  attr_accessible :name

  has_many :posts, :dependent => :destroy
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title, :image

  belongs_to :board, :counter_cache => true
  belongs_to :user

  has_attached_file :image, :styles => { :show => "640x480>", :thumb => "100x100#" }

  scope :recent, :order => "updated_at DESC"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :posts, :dependent => :destroy
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout "admin"
  before_filter :authenticate_admin!

  protected

  def authenticate_admin! #TODO: authenticate_admin, admin_required or require_is_admin
    unless current_user && current_user.is_admin?
      redirect_to root_path, :alert => "You are not admin!"
    end
  end
end

app/controllers/admin/boards_controller.rb
class Admin::BoardsController < Admin::BaseController
  before_filter :find_board, :only => [:show, :edit, :update, :destroy]

  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found

  def index
    @boards = Board.paginate(:page => params[:page], :per_page => 5)
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.create(params[:board])
    if @board
      redirect_to board_path(@board)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @board.update_attributes(params[:board])
      redirect_to board_path(@board), :notice => "Board updated"
    else
      render :edit
    end
  end

  def destroy
    @board.destroy
    redirect_to admin_boards_path, :notice => "Board updated"
  end


  protected

  def find_board
    @board = Board.find(params[:id])
  end

  def record_not_found
    redirect_to admin_boards_path, :notice => "Not found"
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  before_filter :find_board
  before_filter :find_post, :only => [:edit, :update, :destroy]

  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found

  def edit
  end

  def update
    if @post.update_attributes(params[:post])
      redirect_to board_post_path(@board, @post), :notice => "Post has been updated!"
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to board_path(@board), :notice => "Post has been deleted!"
  end

  protected

  def find_board
    @board = Board.find(params[:board_id])
  end

  def find_post
    @post = Post.find(params[:id])
  end

  def record_not_found
    redirect_to board_path(@board), :notice => "Not found"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_filter :find_board, :only => [:show, :edit, :update, :destroy]

  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found

  def index
    @boards = Board.paginate(:page => params[:page], :per_page => 5)
  end

  def show
    @posts = @board.posts.recent.paginate(:page => params[:page], :per_page => 5)
  end

  protected

  def find_board
    @board = Board.find(params[:id])
  end

  def record_not_found
    redirect_to boards_path, :notice => "Not found"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show]

  before_filter :find_board
  before_filter :find_board_post, :only => [:show, :edit]
  before_filter :find_user_post,  :only => [:update, :destroy]

  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found

  def show
  end

  def new
    @post = @board.posts.build
  end

  def create
    @post = @board.posts.build(params[:post])
    @post.user_id = current_user.id
    if @post.save
      redirect_to board_post_path(@board, @post)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update_attributes(params[:post])
      redirect_to board_post_path(@board, @post), :notice => "Post has been updated!"
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to board_path(@board), :notice => "Post has been deleted!"
  end

  protected

  def find_board
    @board = Board.find(params[:board_id])
  end

  def find_board_post
    @post = @board.posts.find(params[:id])
  end

  def find_user_post
    @post = current_user.posts.find(params[:id])
  end

  def record_not_found
    redirect_to board_path(@board), :notice => "Not found"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/boards/_form.html.erb
<div>
<%= f.label :name %>
<%= f.text_field :name %>
</div>


<%= f.submit "Save" %>

app/views/admin/boards/edit.html.erb
<h1>Edit Board</h1>

<%= form_for @board, :url => admin_board_path(@board) do |f| %>
  <%= render "form", :f => f %>
<% end %>

<%= link_to("Back", admin_boards_path) %>

app/views/admin/boards/index.html.erb
<h1>Boards</h1>

<p><%= link_to("Add Board", new_admin_board_path) %></p>

<%= will_paginate @boards %>

<table>
  <tr>
    <th>name</th>
  </tr>
  <% @boards.each do |board| %>
    <tr>
      <td><%= link_to(board.name, board_path(board)) %></td>
    </tr>
  <% end %>
</table>

<%= will_paginate @boards %>

<p><%= link_to("Add Board", new_admin_board_path) %></p>

app/views/admin/boards/new.html.erb
<h1>New Board</h1>

<%= form_for @board, :url => admin_boards_path do |f| %>
  <%= render "form", :f => f %>
<% end %>

<%= link_to("Back", admin_boards_path) %>

app/views/admin/boards/show.html.erb
<h1>Board: <%= @board.name %></h1>
<p>
  <%= link_to("Back", admin_boards_path) %> | 
  <%= link_to("Edit", edit_admin_board_path(@board)) %> | 
  <%= link_to("Destroy", admin_board_path(@board), :method => :delete, :confirm => "Are you sure?") %>
</p>

<hr>
<h2>Posts</h2>

<% if @posts.present? %>
  <% @posts.each do |post| %>
    <h3><%= link_to(post.title, admin_board_post_path(@board, post)) %></h3>
    <p>
      <%= post.content %>
    </p>
    <%= link_to("Edit", edit_admin_board_post_path(@board, post)) %> | 
    <%= link_to("Destroy", admin_board_post_path(@board, post), :method => :delete, :confirm => "Are you sure?") %>
    <hr>
  <% end %>
<% else %>
  <p>
    No post yet :(
  </p>
<% end %>

<p>
  <%= link_to("Add Post", new_admin_board_post_path(@board)) %>
</p>

app/views/admin/posts/_form.html.erb
<div>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</div>

<div>
  <%= f.label :content %><br>
  <%= f.text_area :content %>
</div>

<div>
  <%= f.label :upload_image %><br>
  <%= f.file_field :image %>
  <% if post.image.present? %>
    <div>
      原本的<br>
      <%= image_tag(post.image.url(:thumb)) %>
    </div>
  <% end %>
</div>

<div>
  <%= f.submit "Save" %>
</div>

app/views/admin/posts/edit.html.erb
<h1>Edit Post</h1>

<%= form_for @post, :url => admin_board_post_path(@board, @post), :html => { :mulitpart => true } do |f| %>
  <%= render "form", :f => f, :post => @post %>
<% end %>

<%= link_to("Back", board_path(@board)) %>

app/views/admin/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.content %></p>

<%= link_to("Back", board_path(@board)) %>

app/views/boards/index.html.erb
<h1>Boards</h1>

<%= will_paginate @boards %>

<table>
  <tr>
    <th>name</th>
  </tr>
  <% @boards.each do |board| %>
    <tr>
      <td><%= link_to(board.name, board_path(board)) %></td>
    </tr>
  <% end %>
</table>

<%= will_paginate @boards %>


<hr>

<p>
  這串文字是辨識用：看看cap是否運作成功 2013-09-18 10:39
</p>

app/views/boards/show.html.erb
<h1>Board: <%= @board.name %></h1>
<p>
  <%= link_to("Back", boards_path) %>
  <% if current_user && current_user.is_admin? %>
    <p>
      <%= link_to("A-Edit", edit_admin_board_path(@board)) %> |
      <%= link_to("A-Destroy", admin_board_path(@board), :method => :destroy, :confirm => "Are you sure?") %>
    </p>
  <% end %>
</p>

<hr>
<h2>Posts (共 <%= @board.posts.size %> 篇)</h2>

<p><%= link_to("Add Post", new_board_post_path(@board)) %></p>

<%= will_paginate @posts %>

<table>
  <tr>
    <th>id</th>
    <th>title</th>
    <th>建立時間</th>
    <th>最後更新</th>
  </tr>
  <% if @posts.present? %>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.id %></td>
        <td><%= link_to(post.title, board_post_path(@board, post)) %></td>
        <td><%= post.created_at %></td>
        <td><%= post.updated_at %></td>
      </tr>
    <% end %>
  <% else %>
    <tr>
      <td colspan="4"No post yet :(</td>
    </tr>
  <% end %>
</table>

<%= will_paginate @posts %>

<p><%= link_to("Add Post", new_board_post_path(@board)) %></p>

app/views/common/_user_nav.html.erb
<nav>
  <% if user_signed_in? %>
    Hi! <%= current_user.email %>
    (<%= link_to("Logout", destroy_user_session_path, :method => :delete) %>)
    <% if current_user.is_admin? %>
      | <%= link_to("Admin Panel", admin_boards_path) %>
    <% end %>
  <% else %>
    <%= link_to("Login", new_user_session_path) %> |
    <%= link_to("Sign up", new_user_registration_path) %>
  <% end %>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails101Homework</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "common/user_nav" %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<h1>Admin Panel</h1>
<hr>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails101Homework</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- style? 省略 :partial -->
<%= render "common/user_nav" %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<div>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</div>

<div>
  <%= f.label :content %><br>
  <%= f.text_area :content %>
</div>

<div>
  <%= f.label :upload_image %><br>
  <%= f.file_field :image %>
  <% if post.image.present? %>
    <div>
      原本的<br>
      <%= image_tag(post.image.url(:thumb)) %>
    </div>
  <% end %>
</div>

<div>
  <%= f.submit "Save" %>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= form_for @post, :url => board_post_path(@board, @post), :html => { :mulitpart => true } do |f| %>
  <%= render "form", :f => f, :post => @post %>
<% end %>

<%= link_to("Back", board_path(@board)) %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for @post, :url => board_posts_path(@board), :html => { :mulitpart => true } do |f| %>
  <%= render "form", :f => f, :post => @post %>
<% end %>

<%= link_to("Back", board_path(@board)) %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<%= link_to("Back", board_path(@board)) %>

<div class="post">
  <% if current_user && current_user == @post.user %>
    <%= link_to("Edit", edit_board_post_path(@board, @post)) %> |
    <%= link_to("Destroy", board_post_path(@board, @post), :method => :delete, :confirm => "Are you sure?") %> |
  <% end %>

  <% if current_user && current_user.is_admin? %>
    <%= link_to("A-Edit", edit_admin_board_post_path(@board, @post)) %> |
    <%= link_to("A-Destroy", admin_board_post_path(@board, @post), :method => :delete, :confirm => "Are you sure?") %> |
  <% end %>

  <% if @post.image.present? %>
    <div>
      <%= image_tag(@post.image.url(:show)) %>
    </div>
  <% end %>

  <%= simple_format(@post.content) %>
</div>